apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-operator-backup
  namespace: gitlab
spec:
  template:
    spec:
      containers:
      - name: gitlab-operator
        image: quay.io/samsung_cnct/gitlab-operator:latest
        command: ["/gitlab-operator", "backup", "-s", "superior-gitlab-backups"]
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          value: <REDACTED>
        - name: AWS_SECRET_ACCESS_KEY
          value: <REDACTED>
        - name: AWS_REGION
          value: us-west-2
      serviceAccountName: gitlab-admin
      restartPolicy: Never
  backoffLimit: 3
